version: '2'
services:
  pry:
    build: .
    container_name: teleport
    command: pry -r './lib/workers/analytics_worker.rb'
    env_file: .env
    stdin_open: true
    tty: true
  bash:
    build: .
    container_name: teleport
    command: bash
    env_file: .env
    stdin_open: true
  bundle:
    build:
      dockerfile: Dockerfile.bundle
      context: .
    command: bundle install --system
    container_name: telekinesis-bundle
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
